### PR TITLE
Pokemon added via databrowser are now associatd with a trainer. Datab…

### PR DESCRIPTION
**Pull request by jl-n**
…rowser bug now fixed for safari.

### CODE REVIEW

**Comment by marktani** [comment]
Even though I merged this, I redeployed the previous version.

I think we discussed yesterday that you have to update another endpoint somewhere? That makes sense because with this version we get these errors:

error

**Comment by marktani** [comment]
Can you find out where we have to change this endpoint? I can then prepare a dedicated LA projcect and we use the project id from that project to download the schema.

**Comment by jl-n** [comment]
Ahh shame. Yes, in my case I had to change the endpoint in the graphql field of the package.json file.

**Comment by marktani** [comment]
right! forgot about that. cool, I will take care of that in the evening. :slightly_smiling_face:

**Comment by JulianTapales** [comment]
Awesome :-)

**Comment by marktani** [comment]
done and done! :tada:

**Pull request merged**
