### PR TITLE
Update exercise-03 README.md

### PR DESCRIPTION
**Pull request by bryantheastronaut**
Fixed typos

### CODE REVIEW

**Comment by marktani** [comment]
thanks @bryantheastronaut 🙌

**Comment by bryantheastronaut** [comment]
No problem. Thanks for this project, it's been super helpful!

**Comment by tychota** [comment]
Thank you very much and sorry for my bad English. Don't hesitate to ask if you find something unclear.

**Comment by bryantheastronaut** [comment]
No problem! Happy to help. This tutorial was really helpful! Thank you!

**Pull request merged**
